name: satquery-ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pip:
    - einops==0.6.1
    - einops-exts==0.0.4
    - fastapi
    - gradio==3.35.2
    - markdown2[all]
    - numpy
    - requests
    - sentencepiece==0.1.99
    - tokenizers>=0.12.1
    - uvicorn
    - wandb
    - shortuuid
    - httpx==0.24.0
    - deepspeed==0.9.5
    - peft==0.4.0
    - transformers==4.31.0
    - accelerate==0.21.0
    - bitsandbytes==0.41.0
    - scikit-learn==1.2.2
    - timm==0.6.13
    - gradio_client==0.2.9
    - opencv-python
    - pillow
