name: satquery-ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip>=23.0
  - pytorch=2.2.0
  - torchvision=0.17.0
  - pip:
    - einops==0.8.0
    - einops-exts==0.0.4
    - fastapi
    - gradio==4.0.0
    - markdown2[all]
    - numpy
    - requests
    - sentencepiece
    - tokenizers>=0.12.1
    - uvicorn
    - wandb
    - shortuuid
    - httpx
    - deepspeed
    - peft
    - transformers
    - accelerate
    - bitsandbytes
    - scikit-learn
    - timm
    - gradio_client
    - opencv-python
    - pillow
